### ISSUE TITLE
building on 4.19.1

### ISSUE THREAD

**Issue by kyleacierto** [ue4plugins/StreetMap#39]
is this plugin still able to work on the current patch?

**Comment by h656** [comment]
Hello,
These errors are apparently due to a recent UnrealEngine feature called "Insert What You Use" (IWYU). A quick fix is to modify the build.cs files of the plugin. i.e
Add this line to your build.cs files in your plugin "bEnforceIWYU = false;" to get rid of these errors.
This can then compile on any version of the unreal engine.
UPDATE:
If you are building this above 4.18 Version, follow the below,
In StreetMapComponentDetails.cpp
Line 46: change ".GetSelectedObjects" to "->GetSelectedObjects"
Line 61: chagne ".GetSelectedActors" to "->GetSelectedActors"
Thanks.

**Comment by ajithkrishnan** [comment]
I am building the plugin on 4.19.2 and I copied the "bEnforceIWYU = false;" to all three Build.cs files. However it still fails to build.
I still get these warnings:
LogInit: Warning: Still incompatible or missing module: libUE4Editor-StreetMapRuntime.so
LogInit: Warning: Still incompatible or missing module: libUE4Editor-StreetMapImporting.so

**Comment by n1ckfg** [comment]
Yeah, same for me on 4.19.2. Any advice?

**Comment by h656** [comment]
Hello,

There's a trick to bypass these errors, Don't build the project from visual studio, once you've fixed the above files, save them and now in the project folder, right click on .uproject file and select Generate Visual Studio Files, once done just open the project normally, it will ask you for rebuilding the dlls, let it rebuild. That's it, that should work

**Comment by dotcamdev** [comment]
Mhousse1247 fixed these errors in PR 4.19 & RenderProxy Update #45
