### ISSUE TITLE
I can not run the plugin

### ISSUE THREAD

**Issue by PortalGamerBR** [ue4plugins/StreetMap#7]
I can not run the plugin, the following error messages appear, follow the links of the prints.

http://imgur.com/a/9j6Jv

http://imgur.com/a/BLN2d

**Comment by MikeFricker** [comment]
There are no currently precompiled binaries included, only source code.  So in order to use the plugin, you'll need to put it into a project that has some C++ code in it.  Unreal will automatically compile the plugin binaries when used in a C++ project.  If you want to use it in a Blueprint-only project, you can copy the compiled plugin files from the C++ project into your Blueprint project after the C++ project has been successfully compiled at least once.

**Comment by PortalGamerBR** [comment]
Thanks I'll try.

**Comment by Enrys** [comment]
i have the same problem please tell me exactly how to do
