### ISSUE TITLE
How do I get this to work for 4.25?

### ISSUE THREAD

**Issue by Til-Weimann** [ue4plugins/StreetMap#78]
Hello,
This looks like a great plugin, however I could not get this to run on UE4.25, even after trying several hours and following tips from other people here.
Has anyone here managed to get it running on that version and if yes, how?
Thank you

**Comment by monkatar** [comment]
Hi Til,

Yeah, the user mbpictures made a PR of his fork with a working compile for UE4.24, which I succesfully used to compile and use with 4.25.1 as well. You can get his fork here: https://github.com/ue4plugins/StreetMap/pull/77

Note that the readme/guide seems to be partially invalid with the newer versions of UE4 - you will now have to create a folder called "Plugins" within your target Project and copy the plugin to that folder, then open the Project in UE4 to recompile the code to be able to use it as described.

Hope this helps you.

**Comment by Til-Weimann** [comment]
Thanks, but when I try to open the project after adding the plugin the build fails (Project could not be compiled, try building from source manually).
When attempting to rebuild in Visual Studio the build fails with a lot of errors.
This only happenes if the plugin is in the project folder.
Do you know how I could solve this?

**Comment by monkatar** [comment]
I tried to recreate your scenario from scratch:
- created a new blank project (C++) and named it "PluginTest"
- closed both UE and VS (using VS 2017 Community if that matters)
- put the contents of StreetMap into .../PluginTest/Plugins/StreetMap/
- opened the project up again in UE, the following prompt should show up:
![image](https://user-images.githubusercontent.com/14334836/85204145-afe49d80-b312-11ea-90cf-d804372775ab.png)
- while compiling it does seem to note a few errors (which seem more like warnings due to include conventions) but the compile goes through nontheless
- UE opens up normally and I can drag&drop osm files normally into the viewport to spawn a StreetMapActor
Again, be sure that you're downloading/using the fork with the 4.24 fix: https://github.com/mbpictures/StreetMap

**Comment by Til-Weimann** [comment]
Turns out I just forgot to rename the "StreetMap-master" folder to just "Streetmap".
Thanks a lot for helping!

**Comment by slu11** [comment]
Sorry to open this thread again but what exactly do you put in the VS project? I've never used VS and I don't really understand how/what I need to import into the projects I make. 
Do I just drag the entire OpenStreetMap Source directory into VS?

**Comment by monkatar** [comment]
I don't think you need to open the project in VS at all since the plugin will be recompiled just by opening the project in UE after copying the source to the correct project subfolder. So just copy the source directory into .../<project_folder>/Plugins/ and rename the copied directory to "StreetMap" if not already named that way (see comment from Til-Wimann above), then open the project in UE and it should offer you to recompile the plugin automatically (you should see the window from the screenshot in my post above). Click "yes", wait a bit for it to finish and that should be it.

**Comment by slu11** [comment]
As per your instructions, I added StreetMap to a "Plugins" folder under my project directory. However, I still get compiling errors when I open the project. I've made sure that I renamed the plugin to "StreetMap" and it is still giving me errors. 

![StreetMao](https://user-images.githubusercontent.com/47157655/85573755-2bd93100-b604-11ea-9538-9cd6284cebd2.png)

I've looked in some of my other projects and the plugin I've used before, called TerraForm, is in a different directory but is still a valid plugin. For that one, It's placed in "C:/Program Files/Epic Games/UE_4.24/Engine/Plugins/TerraForm" as opposed to "Documents/Unreal Projects/TFP_T1_TwinMountain/Plugins/StreetMap"

**Comment by slu11** [comment]
Ok so I applied the same steps to version 4.25 of Unreal and it worked. The plugin installed without issue upon compiling. I'm even using the 4.24-optimized version of OpenStreetMap which is kinda of weird. Any ideas on why this might be the case?

**Comment by Jake3231** [comment]
I have been unable to get this to work in 4.25.3. Has anybody had any luck with that?

**Comment by Jake3231** [comment]
> I have been unable to get this to work in 4.25.3. Has anybody had any luck with that?

As an update, the above steps worked as expected after I removed Android support from the Engine on my Mac.
